imports:
  - { resource: parameters.yml }
  - { resource: security.yml }

parameters:
  locale: en
  env(DATABASE_URL): ''

services:
  twig.audit.extension:
    class: AppBundle\Twig\AuditExtension
    tags:
      - { name: twig.extension }
  app.datadog.labeler:
    class: AppBundle\Utils\Labeler
  app.datadog.blamer:
    class: AppBundle\Utils\Blamer
  datadog.event_subscriber.audit:
    class: DataDog\AuditBundle\EventSubscriber\AuditSubscriber
    arguments: ["@security.token_storage"]
    calls:
      -   method: setLabeler
          arguments:
            - '@app.datadog.labeler'
      -   method: setBlamer
          arguments:
            - '@app.datadog.blamer'
    tags:
      - { name: doctrine.event_subscriber, connection: default }

framework:
  secret: "%secret%"
  translator: { fallback: %locale% }
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: true
  form:            ~
  validation:      { enable_annotations: true }
  csrf_protection: ~
  templating:
    engines: ['twig']
  default_locale:  "%locale%"
  trusted_hosts:   ~
  trusted_proxies: ~
  session:
    handler_id: ~
  fragments:       ~
  http_method_override: true
  profiler: { only_exceptions: false }

web_profiler:
  toolbar: true
  intercept_redirects: false

twig:
  debug:            "%kernel.debug%"
  strict_variables: "%kernel.debug%"

doctrine:
  dbal:
    driver:   pdo_sqlite
    host:     "%database_host%"
    port:     "%database_port%"
    dbname:   "%database_name%"
    user:     "%database_user%"
    password: "%database_password%"
    path:     "%database_path%"
    charset:  UTF8

  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true

